"""Add NOC permissions columns to users table

Revision ID: a8c2d4e6f0b1
Revises: f0fb571414ca
Create Date: 2026-02-08 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8c2d4e6f0b1'
down_revision = 'f0fb571414ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_access_noc_dashboard', sa.Boolean(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('can_access_noc_control', sa.Boolean(), nullable=True, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('can_access_noc_control')
        batch_op.drop_column('can_access_noc_dashboard')

    # ### end Alembic commands ###
