"""Add hook_splynx_event table for Splynx webhooks

Revision ID: a9ff15ba0f87
Revises: 919f5a9d12b7
Create Date: 2026-03-01 09:59:57.846829

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a9ff15ba0f87'
down_revision = '919f5a9d12b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hook_splynx_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('ticket_id', sa.String(length=50), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hook_splynx_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hook_splynx_event_processed'), ['processed'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hook_splynx_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hook_splynx_event_processed'))

    op.drop_table('hook_splynx_event')
    # ### end Alembic commands ###
