"""Add resolution_time_minutes field to track total ticket resolution time

Revision ID: f0fb571414ca
Revises: eb1116c82879
Create Date: 2026-02-08 10:13:31.519493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0fb571414ca'
down_revision = 'eb1116c82879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets_detection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolution_time_minutes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets_detection', schema=None) as batch_op:
        batch_op.drop_column('resolution_time_minutes')

    # ### end Alembic commands ###
